/**
 * Handoff Intelligence evaluation fixtures.
 * 20 scenarios × 2 variants (sufficient / insufficient) = 40 cases.
 */

export interface EvalFixture {
  name: string;
  type: string;
  contextPack: Record<string, any>;
  expectedSufficient: boolean;
}

export const fixtures: EvalFixture[] = [
  // --- PM → Dev ---
  { name: 'PM→Dev: complete feature spec', type: 'PM→Dev', expectedSufficient: true, contextPack: { task: 'Implement user profile editing with avatar upload', key_facts: ['Max avatar size 5MB', 'Supported formats: jpg, png, webp', 'Backend uses S3 for storage', 'Auth via JWT'], decisions: [{ decision: 'Use presigned URLs for upload', reason: 'Reduce server load' }], next_steps: ['Create PATCH /users/me endpoint', 'Add S3 presigned URL generation', 'Update schema with avatar_url field'], context: 'Part of user settings revamp, sprint 12' } },
  { name: 'PM→Dev: vague feature request', type: 'PM→Dev', expectedSufficient: false, contextPack: { task: 'Make the profile better', key_facts: [], decisions: [], next_steps: ['Improve it'], context: '' } },

  // --- Dev → QA ---
  { name: 'Dev→QA: complete test handoff', type: 'Dev→QA', expectedSufficient: true, contextPack: { task: 'Test the new handoff send flow with LLM assessment', key_facts: ['POST /:id/send now calls LLM assessment', 'Score >= 70 passes, < 70 triggers auto-supplement', 'Max 3 auto-supplement rounds', 'Fallback returns score 50 on LLM failure'], decisions: [{ decision: 'Use setTimeout for force-send', reason: 'No BullMQ in project yet' }], next_steps: ['Test happy path: score >= 70 sends immediately', 'Test auto-supplement: mock LLM returning score 40', 'Test force-send after 3 rounds', 'Test timeout fallback'], context: 'Handoff intelligence feature, migration 030' } },
  { name: 'Dev→QA: missing test context', type: 'Dev→QA', expectedSufficient: false, contextPack: { task: 'Test the new feature', key_facts: ['Something changed'], decisions: [], next_steps: ['Run tests'], context: '' } },

  // --- Design → Dev ---
  { name: 'Design→Dev: complete design spec', type: 'Design→Dev', expectedSufficient: true, contextPack: { task: 'Implement the new dashboard layout with sidebar navigation', key_facts: ['Figma link: https://figma.com/xxx', 'Breakpoints: 768px, 1024px, 1440px', 'Uses existing design tokens', 'Sidebar collapses on mobile'], decisions: [{ decision: 'Use CSS Grid for main layout', reason: 'Better support for complex layouts' }], next_steps: ['Implement sidebar component', 'Add responsive breakpoints', 'Wire navigation routes'], context: 'Dashboard redesign Q2, approved by product' } },
  { name: 'Design→Dev: incomplete design', type: 'Design→Dev', expectedSufficient: false, contextPack: { task: 'Build the new page', key_facts: ['See Figma'], decisions: [], next_steps: [], context: 'New design' } },

  // --- Dev → Dev ---
  { name: 'Dev→Dev: complete code handoff', type: 'Dev→Dev', expectedSufficient: true, contextPack: { task: 'Take over the payment webhook handler - I am going on leave', key_facts: ['Stripe webhook at /api/webhooks/stripe', 'Handles checkout.session.completed and payment_intent.failed', 'Uses idempotency key in DB to prevent duplicates', 'Retry logic: 3 attempts with exponential backoff'], decisions: [{ decision: 'Store raw event before processing', reason: 'Audit trail and replay capability' }], next_steps: ['Add invoice.paid handler', 'Fix race condition in subscription status update', 'Add monitoring for failed events > 3 retries'], context: 'Payment service in apps/api/src/services/payment.ts, tests in __tests__/payment.test.ts' } },
  { name: 'Dev→Dev: unclear handoff', type: 'Dev→Dev', expectedSufficient: false, contextPack: { task: 'Continue my work', key_facts: ['Check the branch'], decisions: [], next_steps: ['Finish it'], context: '' } },

  // --- Manager → Team ---
  { name: 'Manager→Team: complete sprint planning', type: 'Manager→Team', expectedSufficient: true, contextPack: { task: 'Execute sprint 13 - authentication improvements', key_facts: ['Sprint duration: 2 weeks', 'Team: 3 devs + 1 QA', 'Dependencies: OAuth provider setup complete', 'Blockers: none identified'], decisions: [{ decision: 'Prioritize MFA over SSO', reason: 'Higher security impact, customer requests' }, { decision: 'Use TOTP not SMS', reason: 'Cost and reliability' }], next_steps: ['Dev A: implement TOTP enrollment flow', 'Dev B: implement TOTP verification middleware', 'Dev C: update user settings UI', 'QA: prepare test plan by day 3'], context: 'Q2 security roadmap, approved by CTO' } },
  { name: 'Manager→Team: vague delegation', type: 'Manager→Team', expectedSufficient: false, contextPack: { task: 'Work on auth stuff this sprint', key_facts: [], decisions: [], next_steps: ['Do the auth things'], context: 'Sprint 13' } },

  // --- Dev → DevOps ---
  { name: 'Dev→DevOps: complete deployment request', type: 'Dev→DevOps', expectedSufficient: true, contextPack: { task: 'Deploy handoff-intelligence feature to staging', key_facts: ['Migration 030 needs to run first', 'New env var not needed (uses existing LLM config)', 'No new dependencies added', 'Feature is backward compatible'], decisions: [{ decision: 'Deploy to staging first for 24h', reason: 'LLM integration needs real traffic validation' }], next_steps: ['Run migration 030_handoff_intelligence.sql', 'Deploy api service', 'Verify /handoffs/:id/send returns 202 for low-quality packs', 'Monitor LLM timeout rate'], context: 'PR #142, all tests passing, reviewed by senior dev' } },
  { name: 'Dev→DevOps: incomplete deploy request', type: 'Dev→DevOps', expectedSufficient: false, contextPack: { task: 'Deploy my branch', key_facts: ['Branch: feature/stuff'], decisions: [], next_steps: ['Deploy it'], context: '' } },

  // --- QA → Dev (bug report) ---
  { name: 'QA→Dev: complete bug report', type: 'QA→Dev', expectedSufficient: true, contextPack: { task: 'Fix: handoff send returns 500 when contextPack has null values', key_facts: ['Endpoint: POST /handoffs/:id/send', 'Repro: create handoff with contextPack containing null task field', 'Error: TypeError: Cannot read properties of null', 'Frequency: 100% reproducible', 'Affected version: v2.3.1'], decisions: [{ decision: 'Priority P1', reason: 'Blocks all handoff creation with empty fields' }], next_steps: ['Add null check in validateContextPack', 'Add test case for null fields', 'Verify fix does not break existing valid handoffs'], context: 'Found during handoff-intelligence QA, logs attached in Sentry #4521' } },
  { name: 'QA→Dev: vague bug report', type: 'QA→Dev', expectedSufficient: false, contextPack: { task: 'Something is broken', key_facts: ['It does not work'], decisions: [], next_steps: ['Fix it'], context: '' } },

  // --- PM → Design ---
  { name: 'PM→Design: complete design request', type: 'PM→Design', expectedSufficient: true, contextPack: { task: 'Design the handoff quality indicator UI', key_facts: ['Shows quality score 0-100 as progress ring', 'Color: green >= 70, yellow 40-69, red < 40', 'Shows missing items as checklist', 'Appears on handoff detail page', 'Mobile responsive required'], decisions: [{ decision: 'Use existing design system components', reason: 'Consistency and speed' }], next_steps: ['Create Figma mockup for desktop and mobile', 'Define interaction states (loading, error, success)', 'Review with PM by Thursday'], context: 'Part of handoff intelligence feature, aligns with existing handoff detail page layout' } },
  { name: 'PM→Design: incomplete design request', type: 'PM→Design', expectedSufficient: false, contextPack: { task: 'Design something for quality', key_facts: [], decisions: [], next_steps: ['Make it look good'], context: '' } },

  // --- Tech Lead → Dev ---
  { name: 'TechLead→Dev: complete refactor task', type: 'TechLead→Dev', expectedSufficient: true, contextPack: { task: 'Refactor handoff-webhook.ts to support multiple notification channels', key_facts: ['Current: only webhookUrl (HTTP POST)', 'Target: support webhook, email, and in-app notifications', 'Interface: NotificationChannel with send() method', 'Existing tests cover webhook path'], decisions: [{ decision: 'Strategy pattern for channels', reason: 'Easy to add new channels without modifying core logic' }, { decision: 'Keep backward compatible', reason: 'Existing webhook integrations must not break' }], next_steps: ['Define NotificationChannel interface', 'Extract current webhook logic into WebhookChannel class', 'Add channel registry', 'Update notifyHandoffRecipient to use registry'], context: 'Tech debt item from Q1 retro, estimated 2 days' } },
  { name: 'TechLead→Dev: vague refactor', type: 'TechLead→Dev', expectedSufficient: false, contextPack: { task: 'Clean up the notification code', key_facts: ['It is messy'], decisions: [], next_steps: ['Refactor it'], context: '' } },

  // --- Dev → PM (status update) ---
  { name: 'Dev→PM: complete status update', type: 'Dev→PM', expectedSufficient: true, contextPack: { task: 'Review and approve: handoff intelligence implementation complete', key_facts: ['All 6 deliverables implemented', 'Migration, service, route changes, timeout, fixtures, schema update', 'TypeScript compiles cleanly', 'Follows existing LLM service patterns'], decisions: [{ decision: 'Used setTimeout instead of BullMQ', reason: 'Project has no queue infrastructure yet, setTimeout sufficient for v1' }, { decision: '5-minute timeout for force-send', reason: 'Balance between giving time to supplement and not blocking flow' }], next_steps: ['Run migration on staging DB', 'QA validation of send flow', 'Monitor LLM assessment latency in production'], context: 'Spec: handoff-intelligence-engineering.md, all acceptance criteria met' } },
  { name: 'Dev→PM: unclear status', type: 'Dev→PM', expectedSufficient: false, contextPack: { task: 'Update on my work', key_facts: ['Did some stuff'], decisions: [], next_steps: ['More work needed maybe'], context: '' } },

  // --- Onboarding handoff ---
  { name: 'Onboarding: complete new hire context', type: 'Onboarding', expectedSufficient: true, contextPack: { task: 'Onboard to the AI Drive handoff subsystem', key_facts: ['Monorepo: apps/api (Fastify + Drizzle + PostgreSQL)', 'Handoff flow: draft → sent → received → accepted/rejected/request_more', 'LLM integration via services/llm.service.ts (OpenAI or Anthropic)', 'Auth: JWT via requireAuth plugin', 'Tests: Vitest, fixtures in src/tests/'], decisions: [{ decision: 'Start with handoff routes', reason: 'Most self-contained subsystem for learning' }], next_steps: ['Read apps/api/src/routes/handoffs.ts', 'Read services/handoff-intelligence.ts', 'Run tests locally', 'Try creating and sending a handoff via API'], context: 'New backend engineer starting week of May 26' } },
  { name: 'Onboarding: empty context', type: 'Onboarding', expectedSufficient: false, contextPack: { task: 'Get started on the project', key_facts: [], decisions: [], next_steps: ['Read the code'], context: '' } },

  // --- Incident handoff ---
  { name: 'Incident: complete incident handoff', type: 'Incident', expectedSufficient: true, contextPack: { task: 'Continue investigating: LLM assessment timeout spike (P2)', key_facts: ['Started 2h ago, 40% of assessments timing out', 'OpenAI API latency increased from 2s to 12s', 'Fallback working correctly (returning score 50)', 'No data loss, handoffs still being sent with fallback scores', 'OpenAI status page shows degraded performance'], decisions: [{ decision: 'Do not disable assessment', reason: 'Fallback handles it gracefully' }, { decision: 'Increase timeout to 15s temporarily', reason: 'Capture more real assessments during degradation' }], next_steps: ['Monitor OpenAI status page', 'Revert timeout increase when latency normalizes', 'Consider adding Anthropic fallback for resilience'], context: 'Incident channel #inc-2025-042, on-call rotation handoff at 6pm' } },
  { name: 'Incident: vague incident note', type: 'Incident', expectedSufficient: false, contextPack: { task: 'Something is slow', key_facts: ['LLM is slow'], decisions: [], next_steps: ['Look into it'], context: '' } },

  // --- Cross-team handoff ---
  { name: 'CrossTeam: complete cross-team handoff', type: 'CrossTeam', expectedSufficient: true, contextPack: { task: 'Frontend team: integrate handoff quality indicator', key_facts: ['Backend endpoint: GET /handoffs/:id returns quality_score and quality_warning', 'Score range: 0-100, null means not assessed yet', 'Warning is human-readable string, present only when force-sent', 'API is deployed on staging', 'No new auth requirements'], decisions: [{ decision: 'Show score only after handoff is sent', reason: 'Draft handoffs have no score yet' }], next_steps: ['Add quality badge to handoff detail view', 'Show warning banner when quality_warning is present', 'Add loading state while score is null (assessment in progress)'], context: 'Backend PR merged, staging deployed, contract documented in shared artifacts' } },
  { name: 'CrossTeam: unclear cross-team ask', type: 'CrossTeam', expectedSufficient: false, contextPack: { task: 'Show the quality thing in frontend', key_facts: [], decisions: [], next_steps: ['Add it to the UI'], context: '' } },

  // --- Architecture decision ---
  { name: 'Architecture: complete ADR handoff', type: 'Architecture', expectedSufficient: true, contextPack: { task: 'Implement event sourcing for handoff state transitions', key_facts: ['Current: direct status updates in handoffs table', 'Target: append-only event log + materialized current state', 'Events: HandoffCreated, HandoffSent, HandoffReceived, etc.', 'Storage: new handoff_events table', 'Migration path: dual-write for 2 weeks then cut over'], decisions: [{ decision: 'Dual-write migration strategy', reason: 'Zero downtime, easy rollback' }, { decision: 'Keep current table as materialized view', reason: 'No breaking changes to existing queries' }], next_steps: ['Create handoff_events table migration', 'Implement event writer alongside current updates', 'Add event replay for state reconstruction', 'Write integration tests for dual-write consistency'], context: 'ADR-007 approved, timeline: 3 sprints' } },
  { name: 'Architecture: vague architecture task', type: 'Architecture', expectedSufficient: false, contextPack: { task: 'Move to event sourcing', key_facts: ['Would be better'], decisions: [], next_steps: ['Refactor everything'], context: '' } },

  // --- Security review handoff ---
  { name: 'Security: complete security review', type: 'Security', expectedSufficient: true, contextPack: { task: 'Security review: handoff intelligence LLM integration', key_facts: ['LLM receives full contextPack content', 'No PII filtering before LLM call', 'Uses existing API keys (no new secrets)', 'Timeout prevents resource exhaustion', 'Fallback prevents DoS via LLM unavailability'], decisions: [{ decision: 'Accept PII risk for v1', reason: 'Same risk profile as existing chat feature, PII filtering planned for v2' }], next_steps: ['Verify no API keys or secrets can appear in contextPack', 'Add rate limiting to send endpoint', 'Document PII handling in security docs', 'Plan PII scrubbing for v2'], context: 'Security review checklist item for handoff-intelligence feature launch' } },
  { name: 'Security: incomplete security task', type: 'Security', expectedSufficient: false, contextPack: { task: 'Check if it is secure', key_facts: [], decisions: [], next_steps: ['Review security'], context: 'New feature' } },

  // --- Data migration handoff ---
  { name: 'DataMigration: complete migration handoff', type: 'DataMigration', expectedSufficient: true, contextPack: { task: 'Run migration 030_handoff_intelligence on production', key_facts: ['SQL: 3 ALTER TABLE ADD COLUMN statements', 'All columns have defaults or are nullable', 'No data transformation needed', 'Estimated time: < 1 second (table has ~500 rows)', 'Rollback: ALTER TABLE DROP COLUMN for each'], decisions: [{ decision: 'Run during low traffic window', reason: 'ALTER TABLE takes brief lock on PG 14+' }], next_steps: ['Backup handoffs table', 'Run migration SQL', 'Verify columns exist with correct defaults', 'Deploy API with new schema code'], context: 'Migration file: src/db/migrations/030_handoff_intelligence.sql' } },
  { name: 'DataMigration: unclear migration', type: 'DataMigration', expectedSufficient: false, contextPack: { task: 'Run the migration', key_facts: ['There is a new migration'], decisions: [], next_steps: ['Apply it'], context: '' } },

  // --- Performance optimization ---
  { name: 'Performance: complete perf task', type: 'Performance', expectedSufficient: true, contextPack: { task: 'Optimize handoff list query - currently 800ms for users with 100+ handoffs', key_facts: ['Current query: full table scan with OR condition', 'Missing index on from_user_id and to_user_id', 'Response includes all fields (no projection)', 'User enrichment does N+1 queries'], decisions: [{ decision: 'Add composite index', reason: 'Covers both sender and receiver lookups' }, { decision: 'Batch user lookup', reason: 'Eliminates N+1' }], next_steps: ['Add index: CREATE INDEX idx_handoffs_users ON handoffs(from_user_id, to_user_id)', 'Refactor user enrichment to single IN query', 'Add pagination (limit 50, cursor-based)', 'Benchmark: target < 100ms for 100 handoffs'], context: 'Reported by user with 200+ handoffs, measured via pg_stat_statements' } },
  { name: 'Performance: vague perf complaint', type: 'Performance', expectedSufficient: false, contextPack: { task: 'Make it faster', key_facts: ['It is slow'], decisions: [], next_steps: ['Optimize'], context: '' } },

  // --- Documentation handoff ---
  { name: 'Docs: complete docs task', type: 'Docs', expectedSufficient: true, contextPack: { task: 'Document the handoff intelligence API changes', key_facts: ['POST /:id/send now returns 202 when quality insufficient', 'Response includes assessment object with score, missing, reasoning', 'New fields in handoff response: quality_score, quality_warning, auto_supplement_count', 'Webhook event: handoff.auto_supplement_needed'], decisions: [{ decision: 'Add to existing API docs', reason: 'Keep all handoff docs together' }], next_steps: ['Update POST /send section with new response codes', 'Add quality assessment section', 'Document webhook event payload', 'Add examples for each response scenario'], context: 'API docs in docs/api/handoffs.md, follows OpenAPI-like format' } },
  { name: 'Docs: vague docs request', type: 'Docs', expectedSufficient: false, contextPack: { task: 'Update the docs', key_facts: [], decisions: [], next_steps: ['Write docs'], context: 'Something changed' } },
];
