import type { Agent } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'main',
    name: '牛马',
    emoji: '🐂',
    status: 'online',
    lastHeartbeat: new Date(Date.now() - 2 * 60000).toISOString(),
    tasks: { queue: 0, active: 0, blocked: 0, done: 5 },
  },
  {
    id: 'ad-manager',
    name: 'AD Manager',
    emoji: '📋',
    status: 'online',
    lastHeartbeat: new Date(Date.now() - 1 * 60000).toISOString(),
    tasks: { queue: 0, active: 0, blocked: 0, done: 2 },
  },
  {
    id: 'ad-master',
    name: 'AD Master',
    emoji: '🧭',
    status: 'busy',
    lastHeartbeat: new Date(Date.now() - 30000).toISOString(),
    tasks: { queue: 1, active: 1, blocked: 0, done: 3 },
    currentTask: '龙虾系统监控站架构设计',
  },
  {
    id: 'ad-frontend',
    name: 'AD Frontend Coder',
    emoji: '🎨',
    status: 'busy',
    lastHeartbeat: new Date(Date.now() - 45000).toISOString(),
    tasks: { queue: 1, active: 1, blocked: 0, done: 1 },
    currentTask: 'Dashboard + AgentCard 实现',
  },
  {
    id: 'ad-backend',
    name: 'AD Backend Coder',
    emoji: '⚙️',
    status: 'busy',
    lastHeartbeat: new Date(Date.now() - 60000).toISOString(),
    tasks: { queue: 0, active: 2, blocked: 1, done: 1 },
    currentTask: 'Worker API 开发',
  },
  {
    id: 'ad-tester',
    name: 'AD Tester',
    emoji: '🧪',
    status: 'online',
    lastHeartbeat: new Date(Date.now() - 3 * 60000).toISOString(),
    tasks: { queue: 1, active: 0, blocked: 0, done: 0 },
  },
  {
    id: 'ad-operator',
    name: 'AD Operator',
    emoji: '🚀',
    status: 'offline',
    lastHeartbeat: new Date(Date.now() - 8 * 60000).toISOString(),
    tasks: { queue: 0, active: 1, blocked: 1, done: 0 },
    currentTask: 'Cloudflare 基础设施配置',
  },
];
